
package br.rfdouro.soapclient.client.certidaonascimento;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CertidaoNascimento", targetNamespace = "http://spec.soapservice.rfdouro.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CertidaoNascimento {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://spec.soapservice.rfdouro.br/CertidaoNascimento/calculaIdadeRequest", output = "http://spec.soapservice.rfdouro.br/CertidaoNascimento/calculaIdadeResponse")
    public int calculaIdade(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://spec.soapservice.rfdouro.br/CertidaoNascimento/diaSemanaNascimentoRequest", output = "http://spec.soapservice.rfdouro.br/CertidaoNascimento/diaSemanaNascimentoResponse")
    public String diaSemanaNascimento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
